language: node_js
node_js:
- "10.9"
dist: trusty
sudo: false

cache:
  directories:
  - node_modules

addons:
  chrome: stable

compiler:
  - clang
  - gcc

install: make get-deps

script:
- cd app/view
- npm i
- npm run build --prod --aot
- cd ../background
- npm i
- npm run build --prod --aot
