language: node_js
node_js:
- "8"
dist: trusty
sudo: false

cache:
  directories:
  - node_modules

addons:
  chrome: stable

script:
- cd app/view
- npm run lint
- npm run test:headless
- npm run build --prod --aot
- xvfb-run npm run e2e
- cd ../background
- npm run lint
- npm run test:headless
- npm run build --prod --aot
- xvfb-run npm run e2e
