language: node_js
node_js:
- "10.9"
dist: trusty
sudo: false

cache:
  directories:
  - node_modules

addons:
  chrome: stable

script:
- cd app/view
- npm run build --prod --aot
- cd ../background
- npm i
- npm run build --prod --aot
